### ISSUE TITLE
Error while running the training script

### ISSUE THREAD

**Issue by mrazakhan** [lyutyuh/acl19_subtagger#2]
Hi, I am getting the following error while running the training script.
FileNotFoundError: [Errno 2] No such file or directory: 'https://www.jeffliu.page/files/state.th'

It seems that jeffliu.page website is down. Any idea how to resolve this issue

**Comment by AaronWhite95** [comment]
It‘s OK now

**Comment by jiaweixian** [comment]
sorry, but error happens again. I can download file through link, but error happens while running the training script
