### ISSUE TITLE
BILOU计算问题

### ISSUE THREAD

**Issue by AaronWhite95** [lyutyuh/acl19_subtagger#4]
https://github.com/lyutyuh/acl19_subtagger/blob/227d6b0389a6d01de7c43c229e293ffe09915b3d/modules/hscrf_layer_SoftDict.py#L229
这一行是不是应该注释掉啊，上面已经得到了BILOU_features，为什么又重新置0了呢

**Comment by ShaoQiBNU** [comment]
> https://github.com/lyutyuh/acl19_subtagger/blob/227d6b0389a6d01de7c43c229e293ffe09915b3d/modules/hscrf_layer_SoftDict.py#L229
> 
> 
> 这一行是不是应该注释掉啊，上面已经得到了BILOU_features，为什么又重新置0了呢

hello，你也在复现这套代码吗，可以一起交流一下吗

**Comment by lyutyuh** [comment]
是的，这一行应该注释掉

**Comment by AaronWhite95** [comment]
> > https://github.com/lyutyuh/acl19_subtagger/blob/227d6b0389a6d01de7c43c229e293ffe09915b3d/modules/hscrf_layer_SoftDict.py#L229
> > 
> > 这一行是不是应该注释掉啊，上面已经得到了BILOU_features，为什么又重新置0了呢
> 
> hello，你也在复现这套代码吗，可以一起交流一下吗

是啊
