### ISSUE TITLE
issue while training

### ISSUE THREAD

**Issue by platinum736** [lyutyuh/acl19_subtagger#5]
Hi I am trying to train this on CPU and I am getting the below error. 

result = self.forward(*input, **kwargs)
  File "./models/HSCRF_SoftDict.py", line 228, in forward
    ] += self.end_token_embedding.cuda(util.get_device_of(spans))
RuntimeError: Device index must not be negative

I am not very much aware of torch. Let me know how to resolve it.

**Comment by lyutyuh** [comment]
I think using self.end_token_embedding.cpu() instead of  self.end_token_embedding.cuda(util.get_device_of(spans)) will be fine for cpu.

**Comment by platinum736** [comment]
Thanks @lyutyuh ,
I made the change and it is able to train now.
